sudo: required
dist: trusty
language: php

services:
  - docker

php:
  - 7.1.9

addons:
  chrome: stable
  hosts:
  - localhost
  - mysql

before_install:
  - docker pull selenium/standalone-chrome
  - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome
  - mysql -e 'CREATE DATABASE stockms;'

install:
  - cp .env.dusk.travisci .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - curl http://localhost:4444/wd/hub/status &
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &
  - curl http://localhost &

script:
  - php artisan key:generate
  - php artisan migrate --seed
  - php artisan passport:install
  - php artisan dusk