sudo: required
dist: trusty
language: php

services:
  - mysql
  - nginx

php:
  - 7.1.9

addons:
  chrome: stable

before_install:
  - mysql -e 'CREATE DATABASE stockms;'

install:
  - cp .env.dusk.travisci .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://127.0.0.1 &
  - php artisan key:generate &
  - php artisan migrate --seed &
  - php artisan serve &

script:
  - php artisan dusk