sudo: required
dist: trusty
language: php

services:
  - mysql
  - nginx

php:
  - 7.1.9

addons:
  chrome: stable
  hosts:
  - localhost
  - mysql

before_install:
  - docker pull selenium/standalone-chrome
  - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome
  - mysql -e 'CREATE DATABASE stockms;'

install:
  - cp .env.dusk.travisci .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - php artisan key:generate
  - php artisan migrate --seed
  - php artisan serve

script:
  - php artisan dusk