sudo: required
dist: trusty
language: php

services:
  - docker

php:
  - 7.1.9

addons:
  chrome: stable

before_install:
  - docker pull selenium/standalone-chrome
  - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome
  - cd laradock && cp .env.example .env && docker-compose up -d nginx mysql
  - mysql -e 'CREATE DATABASE stockms;'

install:
  - cp .env.dusk.travisci .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - curl http://localhost:4444/wd/hub/status &
  - curl http://localhost:80/home &

script:
  - php artisan key:generate
  - php artisan migrate --seed
  - php artisan dusk
